baseurl: "/"
languageCode: "en-uk"
title: "Nic Crane"
theme: "hugo-xmin"
googleAnalytics: "UA-116704434-1"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  cpp: "/cpp/:year/:month/:day/:slug/"
  post: "/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: "post/"
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"
    - name: Speaking
      url: "speaking/"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; Nic Crane 2016 -- 2022"
  customJS: ["js/ga.js"]

markup:
  goldmark:
    renderer:
      unsafe: true
